service:
  name: usrv-heros
# this plugins are for using with weback and javascript
plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

#this contains the information about the provider in this case
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: sa-east-1
# $ is to reference variables if stage is undefiende use dev
functions:
  createHero:
    handler: src/handlers/createHero.handler
    events:
      - http:
          method: POST
          path: /hero
#create a custom object
custom:
  bundle:
    linting: false
