service:
  name: usrv-heros
# this plugins are for using with weback and javascript
plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

#this contains the information about the provider in this case
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: sa-east-1
  environment:
    HEROS_TABLE_NAME: ${self:custom.HerosTable.name}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
      Resource:
        - ${self:custom.HerosTable.arn}

resources:
  Resources:
    HerosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: HerosTable-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
  # With Key Schema i'm telling My Attribute id is the key and it is a HASH from string
functions:
  createHero:
    handler: src/handlers/createHero.handler
    events:
      - http:
          method: POST
          path: /hero
  getHeros:
    handler: src/handlers/getHeros.handler
    events:
      - http:
          method: GET
          path: /heros
#create a custom object with !Ref i make a reference to
#Ref can be used with parameters or resources in this case the resource HerosTable and it returns the phisycalID
#With GettAtt we can access to Attributes
custom:
  HerosTable:
    name: !Ref HerosTable
    arn: !GetAtt HerosTable.Arn
  bundle:
    linting: false
